# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mesheryctl < Formula
  desc "The Cloud Native Management Plane."
  homepage "https://layer5.io/meshery"
  version "0.6.0-rc.6fc"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meshery/meshery/releases/download/v0.6.0-rc.6fc/mesheryctl_0.6.0-rc.6fc_Darwin_x86_64.tar.gz"
      sha256 "663105f354f86e167e5636fd75ef7ddc1438145021a7ee5f54aeaadf5a557605"

      def install
        bin.install "mesheryctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meshery/meshery/releases/download/v0.6.0-rc.6fc/mesheryctl_0.6.0-rc.6fc_Darwin_arm64.tar.gz"
      sha256 "7d544e6b48b132180f05c89eb461cf16da08e0d97b8ad3db07ccde6a14d34840"

      def install
        bin.install "mesheryctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/meshery/meshery/releases/download/v0.6.0-rc.6fc/mesheryctl_0.6.0-rc.6fc_Linux_armv6.tar.gz"
      sha256 "5d6ade024fa3dd808cbec9e816884d9ac319c804a203f82b0aff70d6ac4f2e1e"

      def install
        bin.install "mesheryctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/meshery/meshery/releases/download/v0.6.0-rc.6fc/mesheryctl_0.6.0-rc.6fc_Linux_x86_64.tar.gz"
      sha256 "2fb17d0dc38c20a9332f4bf75961b1d2fecd7814898a43cffa8fc3a70371d135"

      def install
        bin.install "mesheryctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meshery/meshery/releases/download/v0.6.0-rc.6fc/mesheryctl_0.6.0-rc.6fc_Linux_arm64.tar.gz"
      sha256 "b4842d18dd2af19194e8d6540fe834f95d858c8fe9f40fb75acb29db06d0efff"

      def install
        bin.install "mesheryctl"
      end
    end
  end
end
